<a href="https://colab.research.google.com/github/SonDog0/PreprocessingSource/blob/main/BERT_TF_Review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q -U tensorflow-text

     |████████████████████████████████| 4.4 MB 7.7 MB/s 


In [ ]:
!pip install -q tf-models-official

     |████████████████████████████████| 1.8 MB 7.9 MB/s 
     |████████████████████████████████| 47.6 MB 36 kB/s 
     |████████████████████████████████| 213 kB 70.2 MB/s 
     |████████████████████████████████| 596 kB 52.3 MB/s 
     |████████████████████████████████| 99 kB 10.3 MB/s 
     |████████████████████████████████| 1.1 MB 65.8 MB/s 
     |████████████████████████████████| 1.2 MB 47.6 MB/s 
     |████████████████████████████████| 90 kB 10.6 MB/s 
     |████████████████████████████████| 352 kB 42.4 MB/s 
     |████████████████████████████████| 43 kB 2.2 MB/s 


In [ ]:
import os
import shutil

import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text
from official.nlp import optimization  # to create AdamW optimizer

import matplotlib.pyplot as plt

tf.get_logger().setLevel('ERROR')

In [ ]:
def print_my_examples(inputs, results):
  result_for_printing = \
    [f'input: {inputs[i]:<30} : score: {results[i][0]:.6f}'
                         for i in range(len(inputs))]
  print(*result_for_printing, sep='\n')
  print()

In [ ]:
def calc_score(score):
  result = ''
  if score >= 0.5:
    result = 'positive'
  else:
    result = 'negative'

  return result


In [ ]:
def review_analysis(df , review_col):
  
  review_list = df[review_col].tolist()
  result = tf.sigmoid(reloaded_model(tf.constant(review_list)))
  result_list = [result[i][0].numpy() for i in range(len(result))]
  df['sentimental score'] = result_list
  df['label'] = df['sentimental score'].apply(calc_score)
  return df



In [ ]:
from google.colab import drive 
drive.mount('/content/gdrive/')

Mounted at /content/gdrive/


In [ ]:
reloaded_model = tf.saved_model.load('/content/gdrive/My Drive/Colab Notebooks/imdb_bert')


In [ ]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv('/content/gdrive/My Drive/Colab Notebooks/review_all_211027.csv' , encoding='utf-8-sig')

In [28]:
df[df['id'] == 'R2M5KAKZZVK1QR']

id  ...                                             review
1256648  R2M5KAKZZVK1QR  ...  I bought 2 different packs by the same seller ...

[1 rows x 3 columns]

In [ ]:
df.tail(5) # 1257078

id  ...   date.unix
1257073  R3RK8T75YL5SM1  ...  1411869600
1257074  R2HE46CV768UPE  ...  1403575200
1257075  R3VJ9JQQJ7NF76  ...  1377655200
1257076  R2SFY59OU8YR54  ...  1371261600
1257077  R21DJC2FU9MPSW  ...  1285898400

[5 rows x 11 columns]

In [ ]:
df_test = df.iloc[:100]

In [17]:
df = df[df['review'].notna()]

In [18]:
df = df[['id' , 'rating' , 'review']]

In [ ]:
len(df)

1255422

In [29]:
step = 1000
slice_num = 0 
cnt = 1256
itter = len(df) 
print('before for')
print(step*1256)
print(int(itter))
for i in range(step*1255 , int(itter) , step):
  print('run for')
  cnt += 1

  
  slice_df = df.iloc[i-step:i]    

  
  if i + step > int(itter):
    print('last')
    slice_df = df.iloc[i-step:]

    

  # print(f'i :{i}')
  # print(f'step : {step}')
  # print(f'df head : {slice_df.head(5)}')
  # print(f'df tail : {slice_df.tail(5)}')
  # print(f'len_df = {len(slice_df)}')
  
  df_sentimental = review_analysis(slice_df , 'review')
  df_sentimental.to_csv(f'/content/gdrive/My Drive/Colab Notebooks/review_all_sentimental/review_all_sentimental_analysis_211102_{cnt}.csv' , encoding='utf-8-sig' , index = False)

print('after for')  






before for
1256000
1255422
run for
last
after for


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


In [ ]:
review_list = df['review'].tolist()

In [ ]:
a = tf.constant(review_list)

In [ ]:
itter = len(a)

In [ ]:
itter

1255422

In [ ]:
total_result_list = []
step = 500
for i in range(0,len(df), step):
  try:
    result = tf.sigmoid(reloaded_model(df.iloc[i-step:i]['review'].tolist()))
  except:
    result = tf.sigmoid(reloaded_model(df.iloc[i-step:]['review'].tolist()))
  
  finally:
    result_list = [result[j][0].numpy() for j in range(len(result))]
    total_result_list += result_list
  

In [ ]:
len(total_result_list)

NameError: ignored

In [ ]:
b = tf.sigmoid(reloaded_model(a[:500]))

In [ ]:
type(b)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
df_sentimental.to_csv('/content/gdrive/My Drive/Colab Notebooks/review_all_sentimental_analysis_1101.csv' , encoding='utf-8-sig' , index = False)

In [ ]:
examples = [
    'this is such an amazing movie!',  # this is the same sentence tried earlier
    'The movie was fucking!',
    'The movie was meh.',
    'The movie was okish.',
    'The movie was terrible...'
]

reloaded_results = tf.sigmoid(reloaded_model(tf.constant(examples)))

In [ ]:
test_exam = ['The movie was terrible...']

In [ ]:
test_result = tf.sigmoid(reloaded_model(tf.constant(test_exam)))

In [ ]:

round(test_result[0][0].numpy(),5)

0.00051

In [ ]:
test_result

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.00051373]], dtype=float32)>

In [ ]:
reloaded_results

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[9.99741e-01],
       [1.03426e-02],
       [9.77522e-01],
       [2.15874e-01],
       [5.13732e-04]], dtype=float32)>

In [ ]:
reloaded_results[2][0].numpy()

0.9775218

In [ ]:
print_my_examples(examples , reloaded_results)

input: this is such an amazing movie! : score: 0.999741
input: The movie was fucking!         : score: 0.010343
input: The movie was meh.             : score: 0.977522
input: The movie was okish.           : score: 0.215874
input: The movie was terrible...      : score: 0.000514

